#!/usr/bin/env python3
"""Generate the deterministic Job Search build stamp.

The stamp is markdown because the shipped runtime surface is markdown-only. This script is dev-side
tooling used by scripts/build.sh and CI; users do not need Python to run the skills.
"""
import argparse
import hashlib
import json
import pathlib
import sys

PUBLISHED_STAMP_URL = (
    "https://raw.githubusercontent.com/agent-data/job-search/main/"
    "shared/references/build-stamp.md"
)
HASH_SCOPE_TEXT = (
    "skills/**, shared/references/**, .claude-plugin/plugin.json, "
    ".codex-plugin/plugin.json; excludes skills/*/evals/** and generated build-stamp.md"
)
PRIMARY_VERSION_MANIFEST = pathlib.Path(".claude-plugin/plugin.json")
EXTRA_HASH_FILES = (
    pathlib.Path(".claude-plugin/plugin.json"),
    pathlib.Path(".codex-plugin/plugin.json"),
)


def _is_generated_stamp(path):
    return path.name == "build-stamp.md"


def _is_skill_eval(path):
    parts = path.parts
    return len(parts) >= 3 and parts[0] == "skills" and "evals" in parts[2:]


def iter_hash_paths(root):
    root = pathlib.Path(root)
    candidates = []
    for base in (root / "skills", root / "shared" / "references"):
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if not path.is_file():
                continue
            rel = path.relative_to(root)
            if _is_generated_stamp(rel) or _is_skill_eval(rel):
                continue
            candidates.append(rel)
    for rel in EXTRA_HASH_FILES:
        if (root / rel).is_file():
            candidates.append(rel)
    return sorted(set(candidates), key=lambda p: p.as_posix())


def read_version(root):
    path = pathlib.Path(root) / PRIMARY_VERSION_MANIFEST
    try:
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
    except OSError as e:
        raise SystemExit(f"{path}: cannot read primary version manifest: {e}") from e
    except ValueError as e:
        raise SystemExit(f"{path}: invalid JSON: {e}") from e
    version = str(data.get("version", "")).strip()
    if not version:
        raise SystemExit(f"{path}: missing non-empty version")
    return version


def content_hash(root):
    root = pathlib.Path(root)
    h = hashlib.sha256()
    for rel in iter_hash_paths(root):
        h.update(rel.as_posix().encode("utf-8"))
        h.update(b"\0")
        h.update((root / rel).read_bytes())
        h.update(b"\0")
    return "sha256:" + h.hexdigest()[:12]


def render_stamp(root):
    version = read_version(root)
    digest = content_hash(root)
    return (
        "# Job Search build stamp\n\n"
        "This file is generated by `scripts/build_stamp.py` through `scripts/build.sh`.\n"
        "Do not edit it by hand.\n\n"
        f"version: {version}\n"
        f"content_hash: {digest}\n"
        "hash_algorithm: sha256-truncated-12\n"
        f"hash_scope: {HASH_SCOPE_TEXT}\n"
        f"published_stamp_url: {PUBLISHED_STAMP_URL}\n"
    )


def main():
    ap = argparse.ArgumentParser(description="Generate the Job Search build stamp.")
    ap.add_argument("--root", default=".")
    ap.add_argument("--write", help="write the stamp to this path as well as stdout")
    args = ap.parse_args()

    root = pathlib.Path(args.root).resolve()
    text = render_stamp(root)
    if args.write:
        out = pathlib.Path(args.write)
        if not out.is_absolute():
            out = root / out
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
