#!/usr/bin/env python3
"""Generate docs/generated/osctl-commands.md from scripts/osctl.py's argparse parser.
Single source of truth = osctl.py; this doc is generated, never hand-edited. Run after changing
osctl's subcommands and commit the result (a CI sync-check enforces it). Stdlib only."""
import argparse, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import osctl  # noqa: E402

REPO = os.path.dirname(HERE)
DOC = os.path.join(REPO, "docs", "generated", "osctl-commands.md")
HEADER = ("<!-- GENERATED by scripts/gen_osctl_docs.py from scripts/osctl.py — do not edit. "
          "Run `python3 scripts/gen_osctl_docs.py` and commit. -->\n")


def generate():
    p = osctl.build_parser()
    sub = next(a for a in p._actions if isinstance(a, argparse._SubParsersAction))
    helps = {ca.dest: (ca.help or "") for ca in sub._choices_actions}
    lines = [HEADER, "", "# osctl commands (generated)",
             "", "`scripts/osctl.py` is the deterministic OS-state CLI the skills call. This table is "
             "generated from its argparse definitions — edit `scripts/osctl.py`, then regenerate.",
             "", "| Command | Arguments | Description |", "|---|---|---|"]
    for name, subparser in sub.choices.items():
        args = []
        for a in subparser._actions:
            if not a.option_strings:        # skip positionals/help-less
                continue
            if a.option_strings == ["-h", "--help"] or "-h" in a.option_strings:
                continue
            args.append("`" + " ".join(a.option_strings) + "`")
        desc = helps.get(name, "").replace("|", "\\|")
        argcell = ", ".join(args) if args else "—"
        lines.append(f"| `{name}` | {argcell} | {desc} |")
    return "\n".join(lines) + "\n"


def main():
    os.makedirs(os.path.dirname(DOC), exist_ok=True)
    with open(DOC, "w", encoding="utf-8") as f:
        f.write(generate())
    print(f"generated {os.path.relpath(DOC, REPO)} ({len(osctl.build_parser()._actions)} top-level actions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
